#!/usr/bin/env python3
"""Generate src/unicode/tables.zig from Python's Unicode database.

Classification, applied in order:

  0 columns  general category Mn, Me, or Cf, except U+00AD SOFT HYPHEN,
             which terminals draw as a visible hyphen
  2 columns  East_Asian_Width W (Wide) or F (Fullwidth)
  1 column   everything else

Only the runs that are *not* one column are emitted, which is what keeps the
table small. Surrogates are forced to one column: they cannot appear in
well-formed UTF-8, and Python reports no useful properties for them.

Usage:
    python3 src/unicode/tools/gen-width-table.py > src/unicode/tables.zig

This is not run by the build. zooi builds with nothing but Zig; regenerating
the table is a deliberate act taken when Unicode is updated.
"""

import sys
import unicodedata

MAX_CP = 0x110000
SURROGATE_LO, SURROGATE_HI = 0xD800, 0xDFFF
UNICODE_VERSION = "16.0.0"


def width_of(cp: int) -> int:
    if SURROGATE_LO <= cp <= SURROGATE_HI:
        return 1
    ch = chr(cp)
    if unicodedata.category(ch) in ("Mn", "Me", "Cf") and cp != 0x00AD:
        return 0
    if unicodedata.east_asian_width(ch) in ("W", "F"):
        return 2
    return 1


def runs():
    """Collapse the codepoint space into (lo, hi, width) runs, skipping width 1."""
    out = []
    start = 0
    prev = None
    for cp in range(MAX_CP):
        w = width_of(cp)
        if w != prev:
            if prev is not None and prev != 1:
                out.append((start, cp - 1, prev))
            prev, start = w, cp
    if prev != 1:
        out.append((start, MAX_CP - 1, prev))
    return out


def check_sorted(name, ranges):
    """A binary search over these is only correct if they are ordered and disjoint."""
    prev_hi = -1
    for lo, hi in ranges:
        if lo > hi:
            sys.exit(f"{name}: inverted range U+{lo:04X}..U+{hi:04X}")
        if lo <= prev_hi:
            sys.exit(f"{name}: overlapping or unsorted at U+{lo:04X}")
        prev_hi = hi


def emit(name, ranges, out):
    out.write(f"pub const {name} = [_]Range{{\n")
    for lo, hi in ranges:
        out.write(f"    .{{ .lo = 0x{lo:04X}, .hi = 0x{hi:04X} }},\n")
    out.write("};\n")


def main():
    if unicodedata.unidata_version != UNICODE_VERSION:
        sys.exit(
            f"requires Unicode {UNICODE_VERSION}; Python provides "
            f"{unicodedata.unidata_version}"
        )
    all_runs = runs()
    zero = [(lo, hi) for lo, hi, w in all_runs if w == 0]
    wide = [(lo, hi) for lo, hi, w in all_runs if w == 2]

    check_sorted("zero_width", zero)
    check_sorted("wide", wide)

    out = sys.stdout
    out.write(
        f"//! Generated by src/unicode/tools/gen-width-table.py from Unicode "
        f"{unicodedata.unidata_version}. Do not edit.\n"
        f"//!\n"
        f"//! Regenerate with:\n"
        f"//!     python3 src/unicode/tools/gen-width-table.py > src/unicode/tables.zig\n"
        f"//!\n"
        f"//! Both arrays are sorted by `lo` and non-overlapping, which is what\n"
        f"//! makes the binary search in width.zig correct.\n"
        f"\n"
        f"pub const Range = struct {{ lo: u21, hi: u21 }};\n"
        f"\n"
    )
    emit("zero_width", zero, out)
    out.write("\n")
    emit("wide", wide, out)


if __name__ == "__main__":
    main()
