#!/usr/bin/env python3
"""Derive benchmark corpus profiles from reference documents.

Reads the licensed reference documents under private/rust-comparison/texts and
emits src/corpora.zig. Only *unigram* statistics leave this script: a code point
frequency table, a word-length distribution and a line-length distribution. No
n-gram, no ordering and no substring of the sources is retained, so the emitted
profiles cannot reconstruct any phrase of the input. The generated file is
checked in; the sources are not, and a normal build never runs this script.
"""
import collections
import pathlib
import sys
import unicodedata

ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCES = ROOT.parent / "private" / "rust-comparison" / "texts"
OUT = ROOT / "corpora.zig"
NAMES = ("arabic", "english", "hindi", "japanese", "korean", "mandarin", "russian", "source_code")
# Quantise weights so the tables stay small and the file stays stable under
# small edits to the sources.
SCALE = 10000


def is_mark(ch):
    return unicodedata.category(ch) in ("Mn", "Mc", "Me")


def quantise(counter, minimum=1):
    total = sum(counter.values())
    out = []
    for key, count in sorted(counter.items()):
        weight = max(minimum, round(count * SCALE / total))
        out.append((key, weight))
    return out


def profile(path):
    text = path.read_text(encoding="utf-8")
    chars = collections.Counter(c for c in text if c not in "\n\r")
    # Words are whitespace-delimited runs; scripts without spaces (CJK) simply
    # produce very long "words", which is the behaviour we want to reproduce.
    words = collections.Counter(len(w) for w in text.split() if w)
    lines = collections.Counter(len(l) for l in text.split("\n"))
    space_ratio = sum(v for k, v in chars.items() if k == " ") / max(1, sum(chars.values()))
    body = collections.Counter({k: v for k, v in chars.items() if k != " "})
    return {
        "chars": quantise(body),
        "marks": {c for c in body if is_mark(c)},
        "words": quantise(words),
        "lines": quantise(lines),
        "space_ratio": space_ratio,
        "bytes": len(text.encode()),
        "distinct": len(body),
    }


def emit_table(out, name, pairs, kind, key=lambda k: k):
    keys = ", ".join(str(key(k)) for k, _ in pairs)
    cum, running = [], 0
    for _, w in pairs:
        running += w
        cum.append(running)
    out.write(f"    pub const {name}_keys = [_]{kind}{{ {keys} }};\n")
    out.write(f"    pub const {name}_cum = [_]u32{{ {', '.join(str(c) for c in cum)} }};\n")


def main():
    if not SOURCES.is_dir():
        raise SystemExit(f"reference documents not found at {SOURCES}; generated file is checked in")
    profiles = {name: profile(SOURCES / f"{name}.txt") for name in NAMES}
    with OUT.open("w", encoding="utf-8") as out:
        out.write("//! Generated by src/tools/generate-corpora.py; do not edit.\n")
        out.write("//!\n")
        out.write("//! Statistical profiles of eight reference documents: a code point frequency\n")
        out.write("//! table, a word-length distribution and a line-length distribution per\n")
        out.write("//! profile. Unigram statistics only - no n-gram, ordering or substring of a\n")
        out.write("//! source document is retained here, so no source text can be reconstructed.\n")
        out.write("//! The reference documents are not part of this repository.\n")
        out.write("//!\n")
        out.write("//! These exist because the repeated-seed corpora in benchmark.zig are\n")
        out.write("//! cache-resident and branch-predictable, which hid a real regression: see\n")
        out.write("//! plans/017 and its acceptance report.\n\n")
        for name in NAMES:
            p = profiles[name]
            out.write(f"/// {name}: {p['distinct']} distinct code points, reference document {p['bytes']} bytes.\n")
            out.write(f"pub const {name} = struct {{\n")
            out.write(f"    pub const space_permille: u32 = {round(p['space_ratio'] * 1000)};\n")
            emit_table(out, "chars", p["chars"], "u21", key=ord)
            marks = sorted(ord(c) for c in p["marks"])
            out.write(f"    pub const marks = [_]u21{{ {', '.join(str(m) for m in marks)} }};\n")
            emit_table(out, "words", p["words"], "u16")
            emit_table(out, "lines", p["lines"], "u32")
            out.write("};\n\n")
        out.write("pub const names = [_][]const u8{ " + ", ".join(f'"{n}"' for n in NAMES) + " };\n")
    print(f"wrote {OUT}")
    for name in NAMES:
        p = profiles[name]
        print(f"  {name:12s} distinct={p['distinct']:4d} space={p['space_ratio']*100:5.1f}% marks={len(p['marks'])}")


if __name__ == "__main__":
    main()
