#!/usr/bin/env python3
"""Generate full default Unicode 17 case-fold mappings (statuses C and F)."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data/CaseFolding-17.0.0.txt"
OUT = ROOT / "tables/case_folding.zig"
MAXCP = 0x110000
BLOCK_SHIFT = 8
BLOCK_SIZE = 1 << BLOCK_SHIFT


def main():
    common, full = {}, {}
    for raw in SOURCE.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        fields = [field.strip() for field in line.split(";")]
        cp, status = int(fields[0], 16), fields[1]
        mapping = tuple(int(value, 16) for value in fields[2].split())
        if status == "C":
            common[cp] = mapping
        elif status == "F":
            full[cp] = mapping
    mappings = common | full
    maximum = max(map(len, mappings.values()))
    assert maximum <= 3, f"full case-fold expansion grew to {maximum}"
    entries = sorted(mappings.items())

    mapping_ids = {cp: i + 1 for i, (cp, _) in enumerate(entries)}
    dense = [mapping_ids.get(cp, 0) for cp in range(MAXCP)]
    blocks, block_ids, block_index = [], {}, []
    for start in range(0, MAXCP, BLOCK_SIZE):
        block = tuple(dense[start : start + BLOCK_SIZE])
        block_id = block_ids.get(block)
        if block_id is None:
            block_id = len(blocks)
            block_ids[block] = block_id
            blocks.append(block)
        block_index.append(block_id)
    assert len(blocks) <= 0x100

    with OUT.open("w", encoding="utf-8") as out:
        out.write("//! Generated by src/tools/generate-case-folding.py; do not edit.\n")
        out.write(f"pub const max_expansion = {maximum};\n")
        out.write(f"pub const table_bytes = {len(block_index) + len(blocks) * BLOCK_SIZE * 2};\n")
        out.write(f"pub const block_shift = {BLOCK_SHIFT};\n")
        out.write("pub const Mapping = struct { codepoints: [3]u21, len: u2 };\n")
        out.write("pub const mappings = [_]Mapping{\n")
        for _, mapping in entries:
            padded = mapping + (0,) * (3 - len(mapping))
            values = ", ".join(f"0x{x:x}" for x in padded)
            out.write(f"    .{{ .codepoints = .{{ {values} }}, .len = {len(mapping)} }},\n")
        out.write("};\n")
        out.write("pub const block_index = [_]u8{\n")
        for i in range(0, len(block_index), 32):
            out.write("    " + ", ".join(map(str, block_index[i:i + 32])) + ",\n")
        out.write("};\n")
        out.write("pub const mapping_ids = [_]u16{\n")
        flat = [value for block in blocks for value in block]
        for i in range(0, len(flat), 16):
            out.write("    " + ", ".join(map(str, flat[i:i + 16])) + ",\n")
        out.write("};\n")
    print(f"wrote {OUT}: {len(entries)} mappings, {len(blocks)} blocks, "
          f"{len(block_index) + len(blocks) * BLOCK_SIZE * 2} lookup bytes, "
          f"max expansion {maximum}")


if __name__ == "__main__":
    main()
