#!/usr/bin/env python3
"""Generate Unicode 17 terminal-facing scalar properties.

The terminal width fields reproduce the derivation used by Ghostty's pinned
uucode revision. Unicode properties remain separate from that width policy.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
OUT = ROOT / "tables/terminal_properties.zig"
MAXCP = 0x110000
SHIFT = 7
BLOCK = 1 << SHIFT

EAW = {"N": 0, "F": 1, "H": 2, "W": 3, "Na": 4, "A": 5}


def records(path):
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        left, value = (part.strip() for part in line.split(";", 1))
        if ".." in left:
            lo, hi = (int(part, 16) for part in left.split("..", 1))
        else:
            lo = hi = int(left, 16)
        yield lo, hi, value


def categories():
    result = ["Cn"] * MAXCP
    pending = None
    for raw in (DATA / "UnicodeData-17.0.0.txt").read_text(encoding="utf-8").splitlines():
        fields = raw.split(";")
        cp, name, category = int(fields[0], 16), fields[1], fields[2]
        if name.endswith(", First>"):
            pending = cp, category
        elif name.endswith(", Last>"):
            lo, saved = pending
            result[lo : cp + 1] = [saved] * (cp + 1 - lo)
            pending = None
        else:
            result[cp] = category
    assert pending is None
    return result


def boolean_property(filename, wanted):
    result = bytearray(MAXCP)
    for lo, hi, prop in records(DATA / filename):
        if prop == wanted:
            result[lo : hi + 1] = b"\x01" * (hi + 1 - lo)
    return result


def main():
    eaw = bytearray(MAXCP)
    for lo, hi in ((0x3400, 0x4DBF), (0x4E00, 0x9FFF),
                   (0xF900, 0xFAFF), (0x20000, 0x2FFFD),
                   (0x30000, 0x3FFFD)):
        eaw[lo : hi + 1] = bytes([EAW["W"]]) * (hi + 1 - lo)
    for lo, hi, value in records(DATA / "EastAsianWidth-17.0.0.txt"):
        eaw[lo : hi + 1] = bytes([EAW[value]]) * (hi + 1 - lo)

    emoji_p = boolean_property("emoji-data-17.0.0.txt", "Emoji_Presentation")
    emoji_modifier = boolean_property("emoji-data-17.0.0.txt", "Emoji_Modifier")
    emoji_modifier_base = boolean_property("emoji-data-17.0.0.txt", "Emoji_Modifier_Base")
    default_ignorable = boolean_property(
        "DerivedCoreProperties-17.0.0.txt", "Default_Ignorable_Code_Point"
    )

    emoji_vs_base = bytearray(MAXCP)
    seen_text = set()
    for raw in (DATA / "emoji-variation-sequences-17.0.0.txt").read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        sequence = line.split(";", 1)[0].split()
        cp, vs = int(sequence[0], 16), int(sequence[1], 16)
        if vs == 0xFE0E:
            emoji_vs_base[cp] = 1
            seen_text.add(cp)
        else:
            assert vs == 0xFE0F and cp in seen_text

    gcb = ["Other"] * MAXCP
    for lo, hi, value in records(DATA / "GraphemeBreakProperty-17.0.0.txt"):
        gcb[lo : hi + 1] = [value] * (hi + 1 - lo)
    gc = categories()

    dense = []
    for cp in range(MAXCP):
        category = gc[cp]
        if category in {"Cc", "Cs", "Zl", "Zp"}:
            standalone = 0
        elif cp == 0x00AD:
            standalone = 1
        elif default_ignorable[cp]:
            standalone = 0
        elif cp == 0x2E3A:
            standalone = 2
        elif cp == 0x2E3B:
            standalone = 3
        elif eaw[cp] in {EAW["W"], EAW["F"]} or gcb[cp] == "Regional_Indicator":
            standalone = 2
        else:
            standalone = 1
        if cp == 0x20E3:
            standalone = 2
        zero = (standalone == 0 or emoji_modifier[cp] or category in {"Mn", "Me"}
                or gcb[cp] in {"V", "T", "Prepend"})
        dense.append(eaw[cp] | emoji_p[cp] << 3 | emoji_vs_base[cp] << 4
                     | emoji_modifier[cp] << 5 | emoji_modifier_base[cp] << 6
                     | standalone << 7 | int(zero) << 9)

    unique, ids, index = [], {}, []
    for start in range(0, MAXCP, BLOCK):
        block = tuple(dense[start : start + BLOCK])
        block_id = ids.get(block)
        if block_id is None:
            block_id = len(unique)
            ids[block] = block_id
            unique.append(block)
        index.append(block_id)
    assert len(unique) <= 0x100

    names = ("neutral", "fullwidth", "halfwidth", "wide", "narrow", "ambiguous")
    with OUT.open("w", encoding="utf-8") as out:
        out.write("//! Generated by src/tools/generate-terminal-properties.py; do not edit.\n")
        out.write("pub const EastAsianWidth = enum(u3) { " + ", ".join(names) + " };\n")
        out.write("pub const WidthProperties = struct { standalone: u2, zero_in_grapheme: bool, emoji_modifier: bool };\n")
        out.write("pub const TerminalProperties = packed struct(u10) { east_asian_width: EastAsianWidth, emoji_presentation: bool, emoji_variation_base: bool, emoji_modifier: bool, emoji_modifier_base: bool, standalone: u2, zero_in_grapheme: bool };\n")
        out.write(f"pub const table_bytes = {len(index) + len(unique) * BLOCK * 2};\n")
        out.write(f"const block_shift = {SHIFT};\n")
        out.write("const index = [_]u8{\n")
        for i in range(0, len(index), 16):
            out.write("    " + ", ".join(map(str, index[i:i + 16])) + ",\n")
        out.write("};\nconst data = [_]u16{\n")
        flat = [item for block in unique for item in block]
        for i in range(0, len(flat), 16):
            out.write("    " + ", ".join(f"0x{x:03x}" for x in flat[i:i + 16]) + ",\n")
        out.write("};\n")
        out.write("fn record(cp: u21) TerminalProperties {\n")
        out.write("    if (cp > 0x10ffff) return @bitCast(@as(u10, 0x280));\n")
        out.write("    const block = index[cp >> block_shift];\n")
        out.write("    return @bitCast(@as(u10, @truncate(data[(@as(usize, block) << block_shift) | (cp & ((1 << block_shift) - 1))])));\n}\n")
        out.write("pub fn terminalProperties(cp: u21) TerminalProperties { return record(cp); }\n")
        out.write("pub fn eastAsianWidth(cp: u21) EastAsianWidth { return record(cp).east_asian_width; }\n")
        out.write("pub fn isEmojiPresentation(cp: u21) bool { return record(cp).emoji_presentation; }\n")
        out.write("pub fn isEmojiVariationBase(cp: u21) bool { return record(cp).emoji_variation_base; }\n")
        out.write("pub fn isEmojiModifier(cp: u21) bool { return record(cp).emoji_modifier; }\n")
        out.write("pub fn isEmojiModifierBase(cp: u21) bool { return record(cp).emoji_modifier_base; }\n")
        out.write("pub fn widthProperties(cp: u21) WidthProperties { const r = record(cp); return .{ .standalone = r.standalone, .zero_in_grapheme = r.zero_in_grapheme, .emoji_modifier = r.emoji_modifier }; }\n")
    print(f"wrote {OUT}: {len(unique)} blocks, {len(index) + len(unique) * BLOCK * 2} bytes")


if __name__ == "__main__":
    main()
